### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#13]
I am using Docker for this project. If I do not include the following command in the Dockerfile:RUN apk add --no-cache git
I get the error:/bin/sh: git: not found
If I add the command, the error changes to:hoyolab-auto | fatal: not a git repository (or any of the parent directories): .git

edit:
I re-cloned the project and added RUN apk add --no-cache git. For now, there haven't been any errors. Also, I want to ask whether the redemption code will automatically redeem the known codes the first time it runs, or will it only redeem new codes thereafter?

**Comment by torikushiii** [comment]
> Also, I want to ask whether the redemption code will automatically redeem the known codes the first time it runs, or will it only redeem new codes thereafter?

The latter, because if I ran code redemption before caching the codes, you would end up redeeming a large number of code redeem.
