### ISSUE TITLE
ZZZ Cookie does not contain account_id_v2 and cookie_token_v2

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#14]
ZZZ Cookie does not contain account_id_v2 and cookie_token_v2. Adding them manually does not solve the problem.

> <WARN:HoyoLab> No cookie_token_v2 or account_mid_v2 found in cookie for nap. This will disable "redeemCode" functionality.

I suggest to add option to read config in old way as an additional functionality.
```
			cookie: {
				token: "", // cookie_token_v2
				mid: "", // account_mid_v2
				ltuid: "" // ltuid_v2
			},
```

**Comment by torikushiii** [comment]
Yes, that is expected. As of commit 11218fe017754bf1fed7b99ce8d47cf5b48b1b75, I've changed how cookies work. You'll need to redo the [cookie guide](https://gist.github.com/torikushiii/59eff33fc8ea89dbc0b2e7652db9d3fd) again, but this time it's much simpler.

**Comment by YozenPL** [comment]
I get it, but it might be strange but my account which I use for Genshin does have cookie_token_v2 and account_mid_v2 in "Cookie" but my new account which I use for ZZZ does not have it.

**Comment by torikushiii** [comment]
I'm assuming that you already tried logging in using incognito mode?

**Comment by YozenPL** [comment]
> I'm assuming that you already tried logging in using incognito mode?

I did it after your suggestion. Now I have those values. Thank you.
