### ISSUE TITLE
[GI] Serenitea Pot - Realm Currency

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#16]
Could you please add Serenitea Pot Realm Currency to track the current count? I believe I saw it in `genshin/api/dailyNote` as `current_home_coin`

**Comment by torikushiii** [comment]
I'm assuming you want so you get notification if your realm currency coin is full?

**Comment by YozenPL** [comment]
Notification sounds better.

**Comment by torikushiii** [comment]
As of commit ed8096f9d9eafd8c29ebcbdba8ff5f85f7a8addb, Realm Currency notification have been added that will look like this

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/f11477f3-7848-4275-93f7-d76d185c2cc0)

**Comment by YozenPL** [comment]
Perfect! Thank you. Do not forgot to change the cron time from 1 min to 30 mins.

**Comment by torikushiii** [comment]
that cron time runs every 1 hour.

**Comment by YozenPL** [comment]
My bad. You are 100% right.
