### ISSUE TITLE
[Suggestion] Option to set cron timers in config.js file

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#17]
Is it possible to move all cron "time configuration" to config.js file?
To have something like:
```
realm-currency_expression: "0 0 * * * *"
stamina_expression: "0 */30 * * * *"
expedition_expression: "0 */30 * * * *"
```
etc...

**Comment by torikushiii** [comment]
Definitely, I'll take a look to it later on how to approach this implementation

**Comment by YozenPL** [comment]
+ some expressions have 6 "parameters" and some have 5

check-in/index.js:      expression: "0 0 0 * * *",  //6
code-redeem/index.js:   expression: "* * * * *", //5
dailies-reminder/index.js:      expression: "0 0 21 * * *", //6
expedition/index.js:    expression: "0 */30 * * * *", //6
missed-check-in/index.js:       expression: "0 0 23 * * *", //6
realm-currency/index.js:        expression: "0 */1 * * *", //5
shop-status/index.js:   expression: "0 */1 * * *", //5
stamina/index.js:       expression: "0 */30 * * * *", //6
weeklies-reminder/index.js:     expression: "0 0 21 * * 0", //6

What is the leading 0 for those with 6 "parameters"?

**Comment by torikushiii** [comment]
Its more like for timing precision

6 parameters indicates that the task should run at the 0th second of the minute. So `0 0 0 * * *` needs to run immediately when the second reach 0 second

5 parameters runs every specified time, at the top of the hour, but not necessarily at the 0th second. So, `0 */1 * * *` runs every hour, at the top of the hour, but not necessarily at the 0th second. It could be a few seconds later, depending on the system's timing precision.

**Comment by torikushiii** [comment]
I've implemented your suggestion at this commit https://github.com/torikushiii/hoyolab-auto/commit/2fc2625d09dc9ce47d65484cd7b4f41089367e42
