### ISSUE TITLE
Redeem code for ZZZ link for manual redeem is not displayed.

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#18]
Redeem code for ZZZ link for manual redeem is not displayed properly.
[Webhook] 
![obraz](https://github.com/torikushiii/hoyolab-auto/assets/4404125/3dfece2f-4e08-4531-a81d-d5c799422f93)

**Comment by YozenPL** [comment]
Ok, my bad. Website for code redemption is not yet available.

**Comment by YozenPL** [comment]
Website: https://zenless.hoyoverse.com/redemption?code=ZZZTVCM

**Comment by torikushiii** [comment]
yep, i just realized that after committing the new resolver, thanks for letting me know.
