### ISSUE TITLE
[Question] Commands - how to use them?

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#19]
In issue #16 you have mentioned "commands". 
I believe we have 4 of them:
- expedition
- notes
- redeem
- stamina

How to use them?

**Comment by torikushiii** [comment]
It's a Discord bot feature only, so if you have a discord bot set up you can just start using them like this `-notes genshin or starrail or zzz` to see your game notes that will looks like this

using `-notes starrail`

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/7b703136-5cc5-45a3-8300-2610b59226d7)

using `-notes zzz`

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/23ad65bc-1456-4b08-935e-beaa69180d90)

`-stamina genshin` will display your current genshin stamina
`-expedition starrail` will display your current expedition status at Star Rail
`-redeem zzz [code]` is just a manual way to redeem codes

**Comment by YozenPL** [comment]
Thank you for explanation. I have one more question but it is not related co commands. Should I ask it here or open new "issue" for it?

**Comment by torikushiii** [comment]
feel free to ask it here

**Comment by YozenPL** [comment]
How often the data/cache.json is updated? What is the logic here? I wanted to use the data from this file for my external display, but it seems it is not refreshing when cron job is executed.

**Comment by torikushiii** [comment]
The cache is stored for 1 hour and will fetch real-time data from Hoyoverse after it expires. During that hour, the cached note data will be internally processed, similar to how Hoyoverse processes stamina and expedition timers, as seen here:

https://github.com/torikushiii/hoyolab-auto/blob/21c298f99d9d3f8a0038454a87e21d95386c0bd2/hoyolab-modules/template.js#L42-L86

The cached data updates every time the `notes` function is called. For example, if this cron runs every 30 minutes:

https://github.com/torikushiii/hoyolab-auto/blob/21c298f99d9d3f8a0038454a87e21d95386c0bd2/crons/stamina/index.js#L1-L3

then the cached data will be updated 30 minutes later.

If you have any further questions about this, feel free to ask.

**Comment by YozenPL** [comment]
Hmm my cache.json file is refreshed every 1h and 30mins. After 2 executions of stamina cron the file was still not refreshed. The 3rd one created new cache. But still, for me only the Resin from Genshin was refreshed. Battery from ZZZ and Realm currency from GI are still at the same count as it was 1,5h earlier.

I believe I need to find the way to fetch Resin, Battery and Realm currency data in some other way.

**Comment by torikushiii** [comment]
Oh yeah, my apologies

I totally forgot to add a function to update GI realm currency internally, and for ZZZ battery it should be auto updated every notes call, but ill take a look. Thanks for letting me know.

**Comment by torikushiii** [comment]
After checking around, it seems ZZZ battery is correctly being updated if the `stamina` cron is called

**Comment by djdoolky76** [comment]
> It's a Discord bot feature only, so if you have a discord bot set up you can just start using them like this `-notes genshin or starrail or zzz` to see your in-game status that will looks like this
> 
> using `-notes starrail`
> 
> ![image](https://private-user-images.githubusercontent.com/21153445/346348879-7b703136-5cc5-45a3-8300-2610b59226d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzU0OTcsIm5iZiI6MTcyMDM3NTE5NywicGF0aCI6Ii8yMTE1MzQ0NS8zNDYzNDg4NzktN2I3MDMxMzYtNWNjNS00NWEzLTgzMDAtMjYxMGI1OTIyNmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1N2FlNTMyNDNmMDEyNWY3NmI4NjRkOTVhYzdhNjM0ZWQ4MTVjZGM2Y2ZiNzVlMWVlMTlmYjA0NWNjZjI4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTI5j2tm1D4r-Ghd3RbOCr2OAHIFAZlbHuyQhkMYkL0)
> 
> using `-notes zzz`
> 
> ![image](https://private-user-images.githubusercontent.com/21153445/346348925-23ad65bc-1456-4b08-935e-beaa69180d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzU0OTcsIm5iZiI6MTcyMDM3NTE5NywicGF0aCI6Ii8yMTE1MzQ0NS8zNDYzNDg5MjUtMjNhZDY1YmMtMTQ1Ni00YjA4LTkzNWUtYmVhYTY5MTgwZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmFmYjc1NTFlZmU1Y2M2OTJkMTgyNmM1MzBkOTA0ZGYwY2RlMGUwY2QyMGZhMmFhZGY4YzkxMjg0MjQ2MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ZWu_XfjrqQKCiTx-cPeKrFGofqkJjXZsE35CrN72z4)
> 
> `-stamina genshin` will display your current genshin stamina `-expedition starrail` will display your current expedition status at Star Rail `-redeem zzz [code]` is just a manual way to redeem codes

it's good if you add -help command in the discord bot that tells what available commands to execute like this

-`stamina genshin` will display your current genshin stamina
-`expedition starrail` will display your current expedition status at Star Rail
-`redeem zzz [code]` is just a manual way to redeem codes

**Comment by torikushiii** [comment]
> it's good if you add -help command in the discord bot that tells what available commands to execute like this
> 
> -`stamina genshin` will display your current genshin stamina -`expedition starrail` will display your current expedition status at Star Rail -`redeem zzz [code]` is just a manual way to redeem codes

I will take your suggestion and will implement it for next commit

**Comment by djdoolky76** [comment]
> > it's good if you add -help command in the discord bot that tells what available commands to execute like this
> > -`stamina genshin` will display your current genshin stamina -`expedition starrail` will display your current expedition status at Star Rail -`redeem zzz [code]` is just a manual way to redeem codes
> 
> I will take your suggestion and will implement it for next commit

I'm looking forward to that but no need to rush anyway 🫡

**Comment by torikushiii** [comment]
> ~After checking around, it seems ZZZ battery is correctly being updated if the `stamina` cron is called~
> 
> I just found out that the note calls does not store into cache file after updated rather it stored at class instead. I should be able to fix this

@YozenPL I've pushed a new commit to potentially fix this https://github.com/torikushiii/hoyolab-auto/commit/5ec145c4cffd99dbcf3e49b9fe8da2e17d13d923 will you try to test it and let me know if it still have a problem

**Comment by YozenPL** [comment]
> > ~After checking around, it seems ZZZ battery is correctly being updated if the `stamina` cron is called~
> > I just found out that the note calls does not store into cache file after updated rather it stored at class instead. I should be able to fix this
> 
> @YozenPL I've pushed a new commit to potentially fix this [5ec145c](https://github.com/torikushiii/hoyolab-auto/commit/5ec145c4cffd99dbcf3e49b9fe8da2e17d13d923) will you try to test it and let me know if it still have a problem

Amazing! I can see the data. Thanks :)
