### ISSUE TITLE
Typo in Dailies Reminder webhook embed.

### ISSUE THREAD

**Issue by reticence96** [torikushiii/hoyolab-auto#20]
There's a typo in the Discord webhook embed where it says "Dalies Reminder" instead of "Dailies Reminder".

https://github.com/torikushiii/hoyolab-auto/blob/5ec145c4cffd99dbcf3e49b9fe8da2e17d13d923/crons/dailies-reminder/index.js#L38

**Comment by torikushiii** [comment]
thanks for letting me know!
