### ISSUE TITLE
[Suggestion] Slash command planned?

### ISSUE THREAD

**Issue by ivanlauhk** [torikushiii/hoyolab-auto#21]
Are you planning to implement slash command for the Discord bot? It's much easier to see the commands and their respective arguments.

**Comment by torikushiii** [comment]
sure, but I've never used slash commands before, so I do need to do some reading. I'll try reading it when I'm free

**Comment by torikushiii** [comment]
Good news, as of commit https://github.com/torikushiii/hoyolab-auto/commit/aa70cff24e0776dbde6b6eacb0027dc11bf259f9, slash commands have been fully implemented, here's how it'll look.

- Command List

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/2458d6d2-187b-4d43-af87-8486d74a2904)

- Usage Example

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/8b045805-3ce4-4e6d-8166-a1f0b61f2229)

**Comment by ivanlauhk** [comment]
Thanks! It works perfectly.
