### ISSUE TITLE
[Question] Google script

### ISSUE THREAD

**Issue by totallynotaguynon** [torikushiii/hoyolab-auto#24]
Does the google script auto-redeem codes as well?

**Comment by torikushiii** [comment]
at the moment, no, since implementing auto-redeem in google script will be somewhat impossible with how the current auto redemption works. i could possibly implement a lite version, but only for codes from livestreams because that's the most feasible option.

**Comment by totallynotaguynon** [comment]
I see is there any other alternative I could use to run the script without having a server/leaving my computer on?

**Comment by torikushiii** [comment]
unfortunately no, if you're trying to use the full project then you'll need to keep it running the whole time. i've tried looking into other hosting servers, but they are not promising so far.

**Comment by torikushiii** [comment]
I will close this issue because of inactivity, if you have any question regarding about this issue, feel free to ask at this issue or open a new one

**Comment by totallynotaguynon** [comment]
I will ask here, one last question, is there a way to setup an autostart or computer boot for the script? I'm in amateur in node or npm.

**Comment by torikushiii** [comment]
if you're using windows, I don't see any good options that can run script on boot other than this project:
- [pm2-installer](https://github.com/jessety/pm2-installer)
- using Windows Task Scheduler, at this guide: https://gist.github.com/torikushiii/d173132267dd907dcbcdf8de12711ee6

if you're using linux based system:
- [pm2](https://pm2.keymetrics.io/)

**Comment by totallynotaguynon** [comment]
Alright thank you
