### ISSUE TITLE
Dailies Reminder, Check-in and Expedition [ZZZ]

### ISSUE THREAD

**Issue by JiLleON** [torikushiii/hoyolab-auto#26]
1. Expeditions are not supported, it seems.
![image](https://github.com/torikushiii/hoyolab-auto/assets/28780165/5367f9aa-daae-44b3-afee-2a0728e31ceb)
2. Is it normal behavior that a daily reminder reminds you even when all the daily tasks are completed? According to starrail-auto, I remember that the notification came only in the case when it was not done by the time of the reminder
![image](https://github.com/torikushiii/hoyolab-auto/assets/28780165/f9a884a2-fbf9-492b-9ee1-389491f12498)
3. Shouldn't there be a notification that if the check-in has already been performed today, then send this notification, and not just write about it in the logs?
![image](https://github.com/torikushiii/hoyolab-auto/assets/28780165/ceab462f-703c-4f1b-9a68-1fed84e7d9f5)

**Comment by JiLleON** [comment]
I also noticed that I did not receive a notification that the check-in was made via missed-check-in. There are no logs anymore, but then I had an older version fixed on commit aa70cff. Perhaps this has already been fixed in the current version.

**Comment by JiLleON** [comment]
Btw how correct would it be to leave the code-redeem value at the current check value every minute? Do I understand correctly that requests for code assembly go online every minute?
I also don't see anything in the logs that concerns checking for the keywords "shop" or "shop-status"

**Comment by torikushiii** [comment]
> If I understand you correctly, `check-in` sends a notification to telegram only when successful. If it detects `already signed in today`, it will not send a notification to telegram about it.

yep, that is correct

> As for `missed-check-in`, it should also send notification to telegram only on successful execution and no notification if `already signed in today`.

`missed-check-in` will not log or send you a notification even on a successful attempt, but i could change that at the next commit so it will send you a notification. the sole reason `missed-check-in` exist is just to silently run in the background and make sure the program didn't missed any check-ins.

> Is it possible to suggest about adding the ability to send `already signed in today` information to telegram? I see that you have added cron black/whitelists. I would put `missed-check-in` in blacklist and not get the extra notification. Or you could rewrite the function so that if the bot received an award, the subsequent `check-in/missed-check-in` would know about it and not send a second notification about it.

I think I could make it to return the data and sends you notification if you've already checked-in

**Comment by torikushiii** [comment]
I've added some of your suggestion to the latest commits, such as:
- Sends notification if you're already checked-in today
- ZZZ expedition message should not throw an error anymore, rather it sends that its not supported

As for Howl Scratch Card, I will add it for the next commit.

Lastly, for redeeming individual code on Telegram, I'll see what I can do since I'm not sure how to implement it.

**Comment by JiLleON** [comment]
@torikushiii oh, that's great. Thank you very much for the work you've done, it will make my experience of interacting with the game more enjoyable and easier.
>Sends notification if you're already checked-in today

On the ac92fc3 version, I got non-stop notifications in telegram this morning that the login was already done after a successful check-in. I will only be able to re-check this behavior after a server reset.
![image](https://github.com/user-attachments/assets/92fa788f-4d49-4e37-8baa-bbbc703b2d74)

>I dont think it will be possible since the current system on Discord is you have a list of the accounts that you can choose

If you are interested, I think a simple solution to this problem is to use the command /redeem. In response to the command comes a message to which attached to the buttons with the choice of account, which are in the config. After clicking on the button with the desired account 'StarRail Nickname1 AR 40' or 'Genshin Nickname2 AR 50' the bot will offer to manually send it the required code. https://core.telegram.org/bots/2-0-intro#new-inline-keyboards
Or there is a method through inline and entering the command redeem, example, `@hoyolab_auto_bot redeem` to display the list of accounts on top. Then the user can click on the desired account, enter and submit the desired code. https://telegram.org/blog/inline-bots

**Comment by torikushiii** [comment]
how about this?

![image](https://github.com/user-attachments/assets/afefe819-35d9-44c5-ac47-2763d4b0e1ff)

**Comment by torikushiii** [comment]
how about this?

![image](https://github.com/user-attachments/assets/d6611da9-7a31-4335-a348-e9aaf8e22661)

**Comment by JiLleON** [comment]
@torikushiii looks comfortable.
>I will only be able to re-check this behavior after a server reset.

I got the logs. Notifications are sent before the end of the minute. Cron value `"check-in": "* 21 1 * * * * *",`
[_hoyolab-auto_logs.txt](https://github.com/user-attachments/files/16199382/_hoyolab-auto_logs.txt)

**Comment by torikushiii** [comment]
i see the problem, there's an unnecessary asterisk "*" at your cron expression change it into this `"check-in": "21 1 * * *"` and you should be fine

**Comment by JiLleON** [comment]
>i see the problem, there's an unnecessary asterisk "*" at your cron expression, change it into this "check-in": "21 1 * * *" and you should be fine.

Oh, I get it. I didn't pay attention to the default.config.js example. If I need to check `shop-status` and `realm-currency` every 15 minutes, it will work fine with this cron value `"*/15 * * * *"` ?

**Comment by torikushiii** [comment]
> Oh, I get it. I didn't pay attention to the default.config.js example. If I need to check `shop-status` and `realm-currency` every 15 minutes, it will work fine with this cron value `"*/15 * * * *"` ?

yes, that is correct.

Thank your for the suggestions, I will add the rest of them.
