### ISSUE TITLE
Regarding the Docker section of the README

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#27]
If you only install Docker without installing Make, you will not be able to use the method described in the README to start the Docker container. You might still need to use the previous method to start it

or install make

**Comment by torikushiii** [comment]
I see, then how about this instruction https://gist.github.com/torikushiii/b0d684d90a65af20b03383d5c4806dfd

**Comment by torikushiii** [comment]
`/bin/sh: git: not found` might be cause by this

https://github.com/torikushiii/hoyolab-auto/blob/d80b21ed59d8349a9c36657d22fe27d3d1386385/crons/code-redeem/resolvers/star-rail/defaults/starrail-api.js#L4-L14

but for the last one, im not so sure yet

**Comment by torikushiii** [comment]
im an absolute idiot, thank you for finding this, i've been trying replicating it myself and totally forgot the `.dockerignore` file
