### ISSUE TITLE
Specify which character you would like to redeem on

### ISSUE THREAD

**Issue by Golumpa** [torikushiii/hoyolab-auto#28]
The config has a message that if you have multiple characters on the same account, eg. different regions. The redemption code will be used but you will not receive any rewards. A simple way around this would be to have an extra option (optional) in the config to specify the uid/region for which character to use the code on.

https://github.com/torikushiii/hoyolab-auto/blob/35f851d36622712b55baa2fa19a0564da8f3da0a/hoyolab-modules/zenless.js#L368-L375

**Comment by torikushiii** [comment]
how about this method? I could try using your approach but I've been stashing this change since yesterday

![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/f6f2a569-d518-47ae-b451-025af0d3cf6d)

**Comment by torikushiii** [comment]
I'm going to close this because of inactivity, but your suggestion should've been implemented just like what I posted the image above. If you have any further question about this, you can comment at this issue or open a new one.
