### ISSUE TITLE
About the Docker auto redeem code

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#29]
Today there is a new redeem code for Star Rail, but it cannot be redeemed correctly

I am very sure that the account has not redeemed this code before
![螢幕擷取1](https://github.com/torikushiii/hoyolab-auto/assets/100028637/d6a88457-7f2b-4759-8a97-851cf9c3d9fd)

and I have re-cloned the git repository and re-composed

edit :
I tried running it locally, but the same issue still occurs

**Comment by torikushiii** [comment]
does it not print any logs at all on the console? I could take a look later

**Comment by torikushiii** [comment]
:/

I just realized that I put a debug only console at the auto redeem code, latest commit should log errors now as it should.

well I guess we need to wait for another new code to see what causes this issue, because the auto-redeemer is work just fine at least for me.

**Comment by torikushiii** [comment]
yep, that's cookie issue, try getting your cookie again
