### ISSUE TITLE
DEBUG is not recognized as a internal or external command

### ISSUE THREAD

**Issue by ScarletDevil25** [torikushiii/hoyolab-auto#3]
Launching the program by doing `node index.js` works however when using `npm start` I get this error

![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/850ed772-0385-4f37-ba5b-f5cfeaaaf46f)

Running on Windows 10 22H2 Build 19045.4412

**Comment by ScarletDevil25** [comment]
I should really run this on my Linux server.

I did the commands however it dosen't log on the console
![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/af71c9be-b0f3-41ac-a426-e88e0f4390c4)

the webhook works howvever I do not see the daily check-in check
![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/21ed7f58-64eb-4fe3-a8e1-69ddbe8caf8b)

**Comment by torikushiii** [comment]
You'll need to one-line it just run this command `set DEBUG=* & node index.js` and You'll start seeing logs

**Comment by ScarletDevil25** [comment]
that works but I should note that `&` only works on cmd and not powershell
