### ISSUE TITLE
Get more detail Google Script

### ISSUE THREAD

**Issue by junoprima** [torikushiii/hoyolab-auto#30]
Can I possibly get the UID and name from this API? Do you have the documentation for the API? I think I can improve it.

**Comment by torikushiii** [comment]
not with the current google script code because fetching UID and name uses different endpoint, which is `https://bbs-api-os.hoyolab.com/game_record/card/wapi/getGameRecordCard`

I could just add an option for people to insert their own UID and Username, that would be more simpler.

**Comment by junoprima** [comment]
ok thank for answer i use in my private discord and many account to know what is that reward

**Comment by torikushiii** [comment]
as of this commit https://github.com/torikushiii/hoyolab-auto/commit/951afd6a5c6a1612200a374ee6b1e71452f6b477

Google Script now returns UID and account name as you can see right here for all games

![image](https://github.com/user-attachments/assets/b6b2b2ae-e0d0-4f11-827f-833404cbaef6)

**Comment by junoprima** [comment]
> as of this commit [951afd6](https://github.com/torikushiii/hoyolab-auto/commit/951afd6a5c6a1612200a374ee6b1e71452f6b477)
> 
> Google Script now returns UID and account name as you can see right here for all games
> 
> ![image](https://private-user-images.githubusercontent.com/21153445/347994950-b6b2b2ae-e0d0-4f11-827f-833404cbaef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTE4MDQsIm5iZiI6MTcyMDc1MTUwNCwicGF0aCI6Ii8yMTE1MzQ0NS8zNDc5OTQ5NTAtYjZiMmIyYWUtZTBkMC00ZjExLTgyN2YtODMzNDA0Y2JhZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAyMzE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYzEwM2FkNWI5ZTZmN2UzMDU0Y2QwZTI3ZmZkYTZkY2YxNjFhNjMzOTRjZDZiZDU5NjFhNGNmNzRhNDg3YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tz34wUwF9XWGo9XgktqWdKME_BzTJwx3cD_RE5746Q0)
> 
> let me know if this is what you wanted.

Thank for reply yes this is what i want before you commit i try to edit code to get that but i got stuck if has multiple game is dupplicate send 
![image](https://github.com/user-attachments/assets/9fb5a838-8854-4051-ab5c-10fe92690f62)
i will try your code :)

**Comment by torikushiii** [comment]
I've updated the google-script to just what you wanted that will looks like this

![image](https://github.com/user-attachments/assets/0632023d-dd98-4273-a66b-683b79d560ea)

**Comment by torikushiii** [comment]
looks good!

**Comment by torikushiii** [comment]
so, im assuming this issue is completed?
