### ISSUE TITLE
Code redeem slash command listing first account from config for GI, HSR and ZZZ instead of accounts for only chosen game.

### ISSUE THREAD

**Issue by reticence96** [torikushiii/hoyolab-auto#31]
When picking an account for a chosen game in the code redeem slash command, it is showing one account each from GI, HSR and ZZZ, instead of the three accounts I have added, for example, in the Genshin Impact section of the config file.

![example](https://github.com/torikushiii/hoyolab-auto/assets/6318072/66f09330-701e-4c38-b481-2b2571a0ab39)

**Comment by torikushiii** [comment]
are you sure that you set this value to `true` on each account?
https://github.com/torikushiii/hoyolab-auto/blob/ac92fc3678f8b2ce9e0d303db427b130adc0b459/default.config.js#L63

**Comment by reticence96** [comment]
Yeah, I have it set to true for each. It's worth mentioning that this is accounts for three different people all on EU servers in each game, rather than seperate regions on one account.

**Comment by torikushiii** [comment]
yep both of my HSR account is a different accounts, try restarting the bot, sometimes discord failed to register the commands properly and it will take a while for discord to update it.
