### ISSUE TITLE
[Genshin Impact] Redemption code

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#38]
Please check if variable which is used for codes can contain the "longer" strings.
Few minutes ago I got notification that script was unable to redeem the code:
`https://genshin.hoyoverse.com/en/gift?code=GENSHINSUMMERNI`
but the real code is:
`https://genshin.hoyoverse.com/en/gift?code=GENSHINSUMMERNIGHT`

Maybe it was cut as variable with code is set to 15 characters max?

+ I got an error on the console:
```
2024-07-17 15:15:04 <INFO:CodeRedeem:Genshin> {
  message: 'Genshin API returned non-zero status code',
  args: {
    retcode: -1071,
    message: {
      data: null,
      message: 'Please log in to your account first',
      retcode: -1071
    }
  }
}

```
Which is strange as I'm logged in (according to the script startup log).

**Comment by torikushiii** [comment]
Oh yeah, thanks for finding that bug, the code is being cutted is my fault, as for the error log, try getting your cookie again and it should work fine

**Comment by YozenPL** [comment]
Thank you. We will see with next "longer" code :)
In the meantime, dunno why but I'm getting this as the output of the console:
2024-07-18 14:00:02 <INFO:Cron:UpdateCookie> Updated cookie for all accounts
```
GENSHINSUMMERNIGHT [
  'Mora ×20000',
  "Hero's Wit ×2",
  'Biryani ×1',
  'Mystic Enhancement Ore ×5',
  'Fruits of the Festival ×1'
]
DUOIMPACT [
  'Primogem ×30',
  "Hero's Wit ×2",
  'Mora ×20000',
  'Sweet Madame ×3',
  'Chicken-Mushroom Skewer ×3'
]
VAJWEZAC7WCZ [ 'Mora ×20000', "Hero's Wit ×2", 'Mystic Enhancement Ore ×5' ]
HHZN6E8685VU [
  'Mora ×10000',
  "Adventurer's Experience ×10",
  'Fine Enhancement Ore ×5',
  'Stir-Fried Fish Noodles ×5',
  'Jueyun Chili Chicken ×5'
]
PXQUNMP48TWM [
  'Mora ×10000',
  "Adventurer's Experience ×10",
  'Fine Enhancement Ore ×5',
  'Stir-Fried Fish Noodles ×5',
  'Jueyun Chili Chicken ×5'
]
JWECZ18L3J49 [
  'Mora ×10000',
  "Adventurer's Experience ×10",
  'Fine Enhancement Ore ×5',
  'Stir-Fried Fish Noodles ×5',
  'Jueyun Chili Chicken ×5'
]
MGCA18HB2727 [
  'Mora ×10000',
  "Adventurer's Experience ×10",
  'Fine Enhancement Ore ×5',
  'Stir-Fried Fish Noodles ×5',
  'Jueyun Chili Chicken ×5'
]

```
Could I suppress it somehow?

**Comment by torikushiii** [comment]
uh, yeah this commit https://github.com/torikushiii/hoyolab-auto/commit/fb3636a9b1998b4e000e992dec5843e5e44fa26d is supposed to fix it 😅, try to pull the latest commit and all of those log will be gone

**Comment by YozenPL** [comment]
Latest pull:
```
2024-07-18 15:00:05 <INFO:CodeRedeem:Genshin> {
  message: 'Genshin API returned non-zero status code',
  args: {
    retcode: -2017,
    message: {
      data: null,
      message: 'This Redemption Code is already in use',
      retcode: -2017
    }
  }
}
```
Could it be formatted like:
```
2024-07-18 15:00:05 <INFO:CodeRedeem:Genshin> CODE_HERE This Redemption Code is already in use
```
?

**Comment by torikushiii** [comment]
Sure, I can do that, thank you for the suggestion

**Comment by torikushiii** [comment]
@YozenPL as of latest commit, error message should display just like what you suggested!

**Comment by torikushiii** [comment]
if you have any more question regarding this issue you can ask here or open a new one!
