### ISSUE TITLE
Bunch of "invalid request"

### ISSUE THREAD

**Issue by AleytiaFairlight** [torikushiii/hoyolab-auto#4]
Webhook is still working 
![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/5d04a9f7-1ea8-4d60-8e51-ed58a6c9dbbd)

But I'm getting "invalid request" error codes in the console, recently synched my fork to yours

![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/9304b588-d3b1-4ecd-a671-6c76c177a3bf)

**Comment by torikushiii** [comment]
Does the error affect any notifications such as check-in, stamina check and the others?

Because the `retcode: -10001` indicates an invalid cookie

**Comment by AleytiaFairlight** [comment]
I waited for daily check-in to get back to you and from observation it seems to be the stamina check thats causing the errors. although it might also be the redeem codes however I have no way to test that atm as there are no redeem codes avail;able atm as far as I know

**Comment by torikushiii** [comment]
I've updated the cookie method into a new one, please follow the [guide again](https://github.com/torikushiii/hoyolab-auto#usage) and see if its resolve the error

**Comment by AleytiaFairlight** [comment]
I was actually observing if I would receive the error again and I belive I have the solution.

your correct that spamming the the end point results in a capcha however if I disable persistent alerts it dosen't trigger anymore. I'm not sure how many requests it takes to trigger but for now it seems stable

**Comment by torikushiii** [comment]
It's just HoyoLab doesn't like their endpoint being spammed with requests in a very short period. I tried it and they flag me as high risk no more than 15 request in very short period, Guess I can just implement a timeouts every request and hope it will go away

**Comment by torikushiii** [comment]
Does this issue still persist for you? If not, you can close this issue for now until it recurs again.

**Comment by torikushiii** [comment]
I'm going to close this issue due to inactivity. If you have any further questions, please feel free to ask in this issue.
