### ISSUE TITLE
Star Rail "Hoyolab returned non--zero retcode"

### ISSUE THREAD

**Issue by Deathfairy27** [torikushiii/hoyolab-auto#41]
Hello torikushii, just wanted to report this to see if its something I coudlve done wrong anywhere.

This popped up right after the daily checkin job started.

![image](https://github.com/user-attachments/assets/4518dde5-354b-4e08-8831-ccc693583362)

**Comment by torikushiii** [comment]
`10035` is related to the captcha error. Try going to your [Battle Records](https://act.hoyolab.com/app/community-game-records-sea/rpg/index.html) page, where you should encounter a captcha that you'll need to solve.

**Comment by Deathfairy27** [comment]
Ah ok good to know, that solved it.
