### ISSUE TITLE
Running on a Raspberry Pi

### ISSUE THREAD

**Issue by Dweller1065** [torikushiii/hoyolab-auto#44]
I'm trying this out on a raspberry pi and I think it's working.
![Untitled](https://github.com/user-attachments/assets/6f1f7f6e-ef85-4c1e-84c5-592e3da9f72c)
Will this continue to run when I exit SSH to my Pi?

**Comment by torikushiii** [comment]
since you ran it directly, then yes.

I recommend you to install [PM2](https://pm2.keymetrics.io/)

**Comment by Dweller1065** [comment]
Thanks. Does this look ok? 
![Untitled](https://github.com/user-attachments/assets/76451540-42db-4c98-a745-77166fab54e4)

**Comment by torikushiii** [comment]
yep, as long your Raspberry Pi didn't shutted down/no internet, then it should run indefinitely

**Comment by Dweller1065** [comment]
Thank you for the help and the cool program!
