### ISSUE TITLE
Discord bot `/redeem` command error - "Please specify a code"

### ISSUE THREAD

**Issue by FlamingFox911** [torikushiii/hoyolab-auto#45]
When I enter `/redeem game Zenless Zone Zero code [anything]`, it always returns `Please specify a code.`

**Comment by torikushiii** [comment]
there's account that you will need to specify, it will look like this

![image](https://github.com/user-attachments/assets/525eb471-93d3-4cdd-ab50-fe1c32b8aa93)

**Comment by FlamingFox911** [comment]
The option for account doesn't show.
![image](https://github.com/user-attachments/assets/cdeb5030-2a17-4df5-b552-5d187ea0fcd3)

**Comment by torikushiii** [comment]
did you tried to restart the script? because sometime discord does not register application commands properly

**Comment by FlamingFox911** [comment]
Ran `make update`. no difference. `down`, `up`, kicked the bot and re-invited with Administrator. No dice.

**Comment by FlamingFox911** [comment]
Ok figured it out. Had to `down` the container, kick the bot, then invite the bot (which came in with the correct slash commands). I then `up` the container.
