### ISSUE TITLE
New 200 Resin count for Genshin

### ISSUE THREAD

**Issue by Deathfairy27** [torikushiii/hoyolab-auto#5]
Hello just figured Id ask is there anything we can adjust in the files to adjust for the new maximum resin in Genshin?

**Comment by torikushiii** [comment]
I totally forgot about that. I'll update the max limit in the next commit.

**Comment by Deathfairy27** [comment]
Sounds good thanks for the great work! Also as a side note not having it at 200 doesn't break anything I still get the web hooks and the web hooks show 200/200.

**Comment by torikushiii** [comment]
as of commit 2e3aa64154143da815a7095aea87a63dedfb489e , I've raised the cap for the resin
