### ISSUE TITLE
Support for Tears of Themis is missing

### ISSUE THREAD

**Issue by nagi-desuuu** [torikushiii/hoyolab-auto#52]
ToT also has it's own check-in page so why not include it too?

**Comment by torikushiii** [comment]
Hello, thank you for your suggestion, Tears Of Themis have been added to the latest commit https://github.com/torikushiii/hoyolab-auto/commit/419b24e7e370290e57d04354f692d1cd17b13e4a

**Comment by torikushiii** [comment]
Yeah, I think I didn't saw any region selection for this game.

**Comment by torikushiii** [comment]
Yeah, sadly there's no an easy way to get TOT account data just like what HI3, GI, and ZZZ does from what I'm seeing right now.
