### ISSUE TITLE
Failed to update cookie

### ISSUE THREAD

**Issue by Lynaia** [torikushiii/hoyolab-auto#56]
I'm getting this error repeatedly after adding a specific account
![image](https://github.com/user-attachments/assets/0dfdf684-0acb-48e2-b6cc-037788232a33)

I had this same error for another account too, but it got resolved after updating the cookie string. It was previously also missing account_mid_v2 and cookie_token_v2 which were throwing other errors.

However, for this particular account all the values seem to be there, and this is the only error associated with it that gets thrown.

**Comment by torikushiii** [comment]
Try the latest commit again and let me know if the error still persist and if it's let me know what's the error message are.

**Comment by Lynaia** [comment]
I haven't seen the error come up since grabbing the latest commit.

On a side note, I did notice a bug where the stamina wasn't being reported properly though.

>Start and initialize application
>I have stamina threshold set at 200
>Logged into game when stamina was 190 before it hit the threshold
>Spend stamina down to 40/240
>1 hour later get a notification saying stamina has reached 200/240
>Check hoyolab battle logs website and it was correctly showing 40/240

I'm not saying the update introduced this bug, as I have noticed the stamina and caching implementation seems to have some pitfalls so this problem might have already existed. Just wanted to let you know that it happened.

**Comment by torikushiii** [comment]
That "should" be fixed at the recent commit.

**Comment by torikushiii** [comment]
@Capoouo latest commit should fix this, since i reverted the changes

**Comment by torikushiii** [comment]
I'm going to close this issue for now but if it occurs someday you can comment here or open a new one!
