### ISSUE TITLE
about config

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#59]
I'm currently creating a documentation webpage for configuring config.json5. I want to ask how to set up multiple accounts for Honkai Impact 3rd and TOT, as I'm a bit unclear on the settings

**Comment by torikushiii** [comment]
it should looks like this

```json
{
    id: 1,
    active: false, // Set to true if you want to enable Honkai Impact 3rd
    type: 'honkai',
    data: [
        // account 1
        {
            cookie: '',
        },
        // account 2
        {
            cookie: '',
        },
        // account 3
        {
            cookie: '',
        },
    ],
},
```

**Comment by torikushiii** [comment]
sure, i would love to see it.

**Comment by torikushiii** [comment]
everything seems to work in order, other than the sticky dark-mode toggle that follows when scrolling down (if that wasn't intended of course)

![gif](https://github.com/user-attachments/assets/6da7c30f-d246-4b52-b1e9-ff7703c17f3b)

**Comment by torikushiii** [comment]
there's a slight issue, at platforms you're missing their id's

https://github.com/torikushiii/hoyolab-auto/blob/d739a39a6f4b6a584989e856bf5405b797424cec/default.config.json5#L4-L26

**Comment by torikushiii** [comment]
> Additionally, I don't understand why the StarRail ID is 3 and the Genshin ID is also 3. Won't there be a conflict?

oh that's my fault and forgot to change it, but it shouldn't be a big problem as im aware of

> If the webpage needs any explanations or titles added, like something about HoYoLAB, just let me know. I haven't incorporated much in terms of aesthetics, LOL

current implementation work just fine

**Comment by torikushiii** [comment]
Alright everything looks good and fine for me and I'm happy with how it looks.

Thank you so much for your contribution for this project!
