### ISSUE TITLE
Failed to log-in

### ISSUE THREAD

**Issue by AleytiaFairlight** [torikushiii/hoyolab-auto#6]
I updated my fork to the latest and subsequently the new cookie structure and it's throwing these please log-in errors which I'm confused about. am I supposed to log into the game?

![image](https://github.com/torikushiii/hoyolab-auto/assets/17516560/1725fd9c-8aa0-411e-bc13-4965dab6185e)

**Comment by torikushiii** [comment]
No, you did not need to log into the game, can you do this instead.

repeat the getting cookie step, but instead of going to the network tab, go to:
1. Application tab
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/b7b9d211-beda-4c54-98b8-e293b6f130a8)

2. And look for `Storage` tab at the left column, then look for Cookies > https://www.hoyolab.com
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/a67fe81c-1945-49c2-9d0f-fa971f22a904)

3. Then look for all the required cookies which is  `account_mid_v2, cookie_token_v2, and ltuid_v2` at the Filter box
> [!NOTE]
> For the `cookie_token_v2` look for the bigger size one

![image](https://github.com/torikushiii/starrail-auto/assets/21153445/692447ab-0925-4a27-8861-6c10c5410520)

4. After that copy the token at the very bottom box
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/a24060a5-7195-4a3e-866f-9f2be17d3c8b)

repeat this for every required cookies

**Comment by AleytiaFairlight** [comment]
> No, you did not need to log into the game, can you do this instead.
> 
> repeat the getting cookie step, but instead of going to the network tab, go to:
> 
> 1. Application tab
>    ![image](https://private-user-images.githubusercontent.com/21153445/336525808-b7b9d211-beda-4c54-98b8-e293b6f130a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTI1MjksIm5iZiI6MTcxNzk1MjIyOSwicGF0aCI6Ii8yMTE1MzQ0NS8zMzY1MjU4MDgtYjdiOWQyMTEtYmVkYS00YzU0LTk4YjgtZTI5M2I2ZjEzMGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDRlYjM4ZDcwY2EyMWU0MGI5YTdhZDZhNGMwMjM1ZGQ1YjQ5ZmM5OTVlMDY5MzRmNzk4NjVkZjZjM2EwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LgUca03qPIm_U4RM15sCcYxETLDs9ZQrTZ0tXC4N1yY)
> 2. And look for `Storage` tab at the left column, then look for Cookies > https://www.hoyolab.com
>    ![image](https://private-user-images.githubusercontent.com/21153445/336530069-a67fe81c-1945-49c2-9d0f-fa971f22a904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTI1MjksIm5iZiI6MTcxNzk1MjIyOSwicGF0aCI6Ii8yMTE1MzQ0NS8zMzY1MzAwNjktYTY3ZmU4MWMtMTk0NS00OWMyLTlkMGYtZmE5NzFmMjJhOTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZmQ0NTczMDA5Y2Y1NzcyZjUxNWE1MmVmMmI2YjYyNjk3YTllYWUxMjAwNTIzNmM2ZWRjYzNmMDczM2UyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1uofTBrfdA07qsCWpO49L5spfmFGU38mH987UtSmQs)
> 3. Then look for all the required cookies which is  `account_mid_v2, cookie_token_v2, and ltuid_v2` at the Filter box
> 
> Note
> 
> For the `cookie_token_v2` look for the bigger size one
> 
> ![image](https://private-user-images.githubusercontent.com/21153445/336530428-692447ab-0925-4a27-8861-6c10c5410520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTI1MjksIm5iZiI6MTcxNzk1MjIyOSwicGF0aCI6Ii8yMTE1MzQ0NS8zMzY1MzA0MjgtNjkyNDQ3YWItMDkyNS00YTI3LTg4NjEtNmMxMGM1NDEwNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZGFhNjI5NjAxYjZjMjA3OTEzNWU0N2FkZjk5NWM1YTA1OGM2ODViOGUxZTc2ZWY4YTExM2UyOGM1YTNkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uJtpWv-9co3NGi5a2a8hrCWPes_yzTbjru78BfKtIzU)
> 
> 4. After that copy the token at the very bottom box
>    ![image](https://private-user-images.githubusercontent.com/21153445/336531254-a24060a5-7195-4a3e-866f-9f2be17d3c8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTI1MjksIm5iZiI6MTcxNzk1MjIyOSwicGF0aCI6Ii8yMTE1MzQ0NS8zMzY1MzEyNTQtYTI0MDYwYTUtNzE5NS00YTNlLTg2NmYtOWYyYmUxN2QzYzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE2NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYmViMzhkMzBiOGY5ZTE2OWJmMDE5Zjc3OTRhMWI2YWYzYTFmYTYxZTk1NjgxMThjZDc5MDIwNmU1YTI0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rn_NO__VLjwb2H3gXXy8YdMyqSV1FuSgiJuxPh7ezy4)
> 
> repeat this for every required cookies

interesting, this gives a different cookie than going to the profile page. I'm able to log-in now but I think you should use this for getting the cookies instead of the currenmt guide
