### ISSUE TITLE
Code redeem in google script

### ISSUE THREAD

**Issue by junoprima** [torikushiii/hoyolab-auto#63]
i see on code it's possible to use redeem in google script :)

**Comment by torikushiii** [comment]
you mean like auto redeem new codes?

**Comment by junoprima** [comment]
Yes i mean like that

**Comment by torikushiii** [comment]
I don't think I can integrate it into the current script because it runs on timers that execute every midnight. Unless you want to check for new codes while the check-in script is running?

**Comment by junoprima** [comment]
i see your updated ran and got error 

ParseError: Unexpected token ILLEGAL 371 .gs

**Comment by junoprima** [comment]
I see redeem code not redeem with Loop multiple Game ? Only Redeem 1

**Comment by torikushiii** [comment]
yes, code redeem feature requires you to provide full cookie, you can follow the guide again [here](https://github.com/torikushiii/hoyolab-auto/tree/main/services/google-script)

**Comment by junoprima** [comment]
I think it's same as before to go to page check-in ?

**Comment by torikushiii** [comment]
@junoprima oh yeah, that one is on me.

you can try again, i've updated the code again
