### ISSUE TITLE
Genshin Code auto redeem

### ISSUE THREAD

**Issue by djdoolky76** [torikushiii/hoyolab-auto#65]
I noticed when the auto redemption code from the live stream picked the CN version codes instead of global codes. My account is OS Asia, anyway. I hope to make some improvements/fixes to this in the future.

![image](https://github.com/user-attachments/assets/4ff11da1-ca7f-4339-a102-c674d5524171)

**Comment by djdoolky76** [comment]
This only happens from Genshin livestream codes. I haven't noticed yet from other or non-related livestream codes

**Comment by torikushiii** [comment]
thanks for the report, this issue should be fixed in the latest commit.
