### ISSUE TITLE
Error when adding the Discord webhook link to Google Script

### ISSUE THREAD

**Issue by cekra007** [torikushiii/hoyolab-auto#68]
Does the script from [link](https://github.com/torikushiii/hoyolab-auto/blob/main/services/google-script/index.js) already include running a Discord webhook? I don't know how to make the script work again.

![webhook1](https://github.com/user-attachments/assets/83e06320-e398-4299-957c-14bb8be5accf)

**Comment by torikushiii** [comment]
you need to put quotes at your discord webhook url

instead of this:
const DISCORD_WEBHOOK = https://discord.com/api/webhooks/

do this
const DISCORD_WEBHOOK = "https://discord.com/api/webhooks/"

**Comment by cekra007** [comment]
Thank you, today I tried the webhook again and it worked, but for Honkai Impact, the notification did not appear on Discord. Here is the log from Google Script.

![webhook2](https://github.com/user-attachments/assets/f7aa2353-382d-4a0e-8372-bf078c70c720)

**Comment by torikushiii** [comment]
should be fixed on latest commit now 👍
