### ISSUE TITLE
Cant login ZZZ

### ISSUE THREAD

**Issue by NaufalF22** [torikushiii/hoyolab-auto#72]
![image](https://github.com/user-attachments/assets/c6704c20-4b55-4d95-b9c1-df9acd1eb3f7)
I can login genshin and HSR but cant login ZZZ, if you translate the chinese word it says "The network is out of commission, please try again later~"

**Comment by WiLuX-Source** [comment]
https://github.com/canaria3406/hoyolab-auto-sign/issues/52

You can use this script in the meantime if you want.

**Comment by torikushiii** [comment]
Have you update the script to the latest commit? This already have been fixed yesterday.

**Comment by NaufalF22** [comment]
![image](https://github.com/user-attachments/assets/42ab08b6-8141-4bca-889b-9d3e40a149ed)
Okay its fix now
