### ISSUE TITLE
App restarts exhaust Discord bot rate limits

### ISSUE THREAD

**Issue by JustArion** [torikushiii/hoyolab-auto#73]
This took me a little while to track down so I'll explain from the beginning.

I found the instance restarting and throwing an exception of `Not enough sessions remaining to spawn 1 shards; only 0 remaining; resets at {date}` every time. I tracked this down to the discord.js' bot being rate limited.

I shut down the docker instance and waited for the rate limit to pass (non-trivial amount of time (eg. like 12-24 hrs)
Discord gives you 1000 shard instances per 24hrs is my guess.

Okay, and fatal exception again, one of my accounts needs to re-login to the game. This likely caused a [docker-compose.yml](https://github.com/torikushiii/hoyolab-auto/blob/main/docker-compose.yml#L8) exception loop which in turn exhausted the discord bot's rate limits due to the bot starting **first** then the normal game exception occurring.

#### Proposal:
Move the [index.js:L62](https://github.com/torikushiii/hoyolab-auto/blob/main/index.js#L62) code lower in the execution chain, preferably after all logins have occurred.

Alternatively we could move to a limit on restarts using the [on-failure](https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy) restart policy allowing a max-retries specifier.

**Comment by torikushiii** [comment]
I've committed a change to move the platforms initialization after logins and added a restart policy to the docker-compose file.

Let me know if this works for you.

**Comment by JustArion** [comment]
> I've committed a change to move the platforms initialization after logins and added a restart policy to the docker-compose file.
> 
> Let me know if that works for you.

This did the trick! Thanks!
