### ISSUE TITLE
Change redemption in Google Script to do the same scraping as the docker instance?

### ISSUE THREAD

**Issue by Aida-Enna** [torikushiii/hoyolab-auto#74]
The API that you're using for the Google Script code redeems doesn't seem to be updating, or updates once every 2? weeks. For example, it didn't have one of the codes for a week and a half, and now it doesn't have the two newest codes in there despite parsing [Prydwen](https://www.prydwen.gg/star-rail/) in it's source.

I made an [issue on their API github](https://github.com/seriaati/hoyo-codes/issues/52) but haven't received a response (or fix) in 2 weeks.

I'm not sure if it's just HKRPG either. Sorry for the trouble!

If this is too outside the scope of the google script (which I would understand!), just let me know and I'll switch to the docker instance.

**Comment by torikushiii** [comment]
I'm pretty sure Google Apps Script doesn't support web scraping, but then again, its main purpose is for handling simple tasks like automating check-ins. I could look around for anyone hosting an API for the codes; the only one I currently know about is this one Star Rail API [https://api.ennead.cc/starrail/code](https://api.ennead.cc/starrail/code).

**Comment by torikushiii** [comment]
Hello, I've updated the API endpoint to use `https://api.ennead.cc/mihoyo` which I've been working this whole weekend (hoyoverse-api)[https://github.com/torikushiii/hoyoverse-api], now the Google Script should be updated and start using the new API.
