### ISSUE TITLE
error when running in armbian

### ISSUE THREAD

**Issue by cekra007** [torikushiii/hoyolab-auto#76]
Hi, I have a Set-Top Box that has been modified to run Linux Armbian. When I followed the installation procedure, I encountered an error as shown in the image. Could you help identify what might be causing the issue? I will also provide the log if the image is not clear enough.
![Cuplikan layar 2024-11-27 170518](https://github.com/user-attachments/assets/4c61fd06-7f17-4964-9570-d9785e10c173)
[2024-11-27T09_16_30_856Z-debug.log](https://github.com/user-attachments/files/17933883/2024-11-27T09_16_30_856Z-debug.log)

**Comment by torikushiii** [comment]
The issue is caused by the Node.js version. Your current version is `node@v14.17.0`. Try updating to the latest LTS or at least a version that is `v20+`.
