### ISSUE TITLE
ZZZ/HSR Code Redeem requires different cookies

### ISSUE THREAD

**Issue by ServePeak** [torikushiii/hoyolab-auto#77]
If I'm not mistaken, the cookies required for check-in and code redemption are different for at least these two games.
Check-in requires:
`ltoken_v2, ltmid_v2, ltuid_v2`
Code redeem requires:
`cookie_token_v2, account_mid_v2, account_id_v2`

Where the mid and uid map, the tokens do not.

If this is the case for others, the instructions should be updated to grab the cookies from the redemption urls as well and just include the additional info in the header.

**Comment by torikushiii** [comment]
The check-in page already provides the full cookie to either check in or redeem codes, if I recall correctly, but I can update the documentation just in case they’ve changed something.

**Comment by torikushiii** [comment]
I've updated the documentation at latest commit 0d4166a0d70bbee55660f79753cdc08414955b87. 

Let me know if you have any questions or need clarification about the cookie retrieval methods.

Method 1 is kept for basic check-in functionality, while Method 2 is recommended for users who want to use both check-in and code redemption features.

**Comment by ServePeak** [comment]
I got a second person to try, and interestingly they do get all the correct cookies. The difference being I don't play genshin and they do.

**Comment by torikushiii** [comment]
![image](https://github.com/user-attachments/assets/16200953-13e1-4b23-83f7-012addf1fac8)

Works fine for me. Try logging into your HoYoLAB profile via incognito mode to see if it resolves the problem.

**Comment by ServePeak** [comment]
that indeed did.

**Comment by torikushiii** [comment]
I'm assuming all good now?

**Comment by ServePeak** [comment]
Yep, the hoyolab works correctly now. Will close
