### ISSUE TITLE
Code redeems while not enabled.

### ISSUE THREAD

**Issue by MoonieGZ** [torikushiii/hoyolab-auto#79]
Hello, I've noticed since adding a second Genshin account to my config that it's still trying to redeem codes despite my config telling it not to? This only started happening when I added the second Genshin and ZZZ accounts, it wasn't redeeming them when only 1 account was configured.

Wondering if this problem has been noticed before?

![image](https://github.com/user-attachments/assets/4169c283-cbcd-40ef-aecd-a5eebfd92266)

Including my config with sensitive data snipped:
[baseconfig.json](https://github.com/user-attachments/files/18270444/baseconfig.json)

You'll notice redeemCode is false for HSR and Genshin but is still running, I wanted to keep them disabled because of the issue you have documented, I have accounts on multiple servers so didn't want to risk losing out.

Can provide more info if needed, thank you!

**Comment by torikushiii** [comment]
Yeah, sorry about that. I forgot to check if the account has `redeemCode: false` during the code redemption. The latest commit should fix this.

**Comment by MoonieGZ** [comment]
Thank you for the quick answer!
