### ISSUE TITLE
Just updated getting error

### ISSUE THREAD

**Issue by Deathfairy27** [torikushiii/hoyolab-auto#8]
Just a question, I just updated my files to the latest and since Ive been getting these errors, any explanation? Rather is it anything to be worried about?
![NVIDIA_Overlay_EyJ5RjcDXo](https://github.com/torikushiii/hoyolab-auto/assets/171508804/908d8df1-7eba-4e5f-93a9-e670d8463d02)

**Comment by torikushiii** [comment]
That's weird, that error indicates it failed to create a cache folder. Can you try creating the folder manually?

Create a new folder called `data`, then create a file named `cache.json`. That should fix the error.

**Comment by Deathfairy27** [comment]
Here is what happens after doing what you said above.
![NVIDIA_Overlay_r9CwH3YUof](https://github.com/torikushiii/hoyolab-auto/assets/171508804/213deded-7d84-4586-bc2f-081d8ddc4947)

**Comment by torikushiii** [comment]
Interesting, try deleting `cache.json` and running it again to see if it still throws an error.

**Comment by Deathfairy27** [comment]
By the looks of it deleting it causes the first error to come back
![NVIDIA_Overlay_ohZSfADyGq](https://github.com/torikushiii/hoyolab-auto/assets/171508804/8cfdbb0f-7d67-4217-9d7f-530ee51c1615)

I'll note; as a just in case I deleted and repulled the repository and made a whole new local copy of it, going through the noted install steps.

**Comment by torikushiii** [comment]
I've tried this on my Windows machine using Node.js `v20.15.0` and didn't encounter any related errors.

You can try one last method to see if it fixes the problem. If it does, I'll simply create a placeholder value for the cache file in the future.

Create a file named `cache.json` in the `data` folder. Edit `cache.json` and paste the following value, then save it:
```json
{"cache":[],"lastExpire":1720082513486}
```

Then it should look like this
![image](https://github.com/torikushiii/hoyolab-auto/assets/21153445/8e345089-bab5-4d7b-a2c3-77195b1cc592)

**Comment by Deathfairy27** [comment]
All that's left after doing that is this
![image](https://github.com/torikushiii/hoyolab-auto/assets/171508804/b7aa824a-5995-4bcb-9a1b-235b03f84898)

**Comment by torikushiii** [comment]
That log message indicates that you're running it using `DEBUG=*` or any similar parameters. Could you try running it using `node index.js` or `npm start` instead?

**Comment by Deathfairy27** [comment]
Oh you are absolutely right, cleared it right up, all good to go!
