### ISSUE TITLE
Auto Code Redemption

### ISSUE THREAD

**Issue by StayBlue** [torikushiii/hoyolab-auto#9]
Are there any plans to add an auto code redemption feature? The idea is to fetch and redeem codes automatically. I will potentially look into implementing this myself if I get the time.

**Comment by StayBlue** [comment]
> It currently appears to have an auto code redemption feature, but the part for zzz has not been added yet By the way, the feature isn't mentioned in the README LOL

💀

**Comment by torikushiii** [comment]
I totally forgot to update the README text to includes the auto-redeem as a feature.

but yes, code-reedem function have been added already as you can see on here https://github.com/torikushiii/hoyolab-auto/tree/main/crons/code-redeem/resolvers, but only for Genshin and Star Rail for now, I will try to add later today for ZZZ

**Comment by StayBlue** [comment]
I'll keep this issue as a tracker so this feature can be documented in the README.

**Comment by torikushiii** [comment]
as of this commit https://github.com/torikushiii/hoyolab-auto/commit/2d0cfa84c76cd0675c20a012e06f3c09649b9ffb, code-redemption feature have been properly documented.
